# Generated by Django 6.0.4 on 2026-04-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_item_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('stripe_coupon_id', models.CharField(blank=True, help_text='ID купона из Stripe Dashboard (например: SAVE10)', max_length=255, verbose_name='Stripe Coupon ID')),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, help_text='Только для отображения. Реальное значение берётся из Stripe.', max_digits=5, null=True, verbose_name='Percent off (%)')),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, help_text='Только для отображения. Реальное значение берётся из Stripe.', max_digits=10, null=True, verbose_name='Amount off')),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('stripe_tax_rate_id', models.CharField(blank=True, help_text='ID налоговой ставки из Stripe Dashboard (например: txr_xxxxx)', max_length=255, verbose_name='Stripe Tax Rate ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Только для отображения. Реальное значение берётся из Stripe.', max_digits=5, verbose_name='Percentage (%)')),
                ('inclusive', models.BooleanField(default=False, verbose_name='Inclusive (уже включён в цену)')),
            ],
            options={
                'verbose_name': 'Tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD — US Dollar'), ('eur', 'EUR — Euro')], default='usd', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discount', verbose_name='Discount')),
                ('items', models.ManyToManyField(to='shop.item', verbose_name='Items')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.tax', verbose_name='Tax')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
